---
- hosts: netbox
  become: true
  become_user: root
  tasks:

  - name: import elasticsearch PGP key
    shell: |
      wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg 

  - name: install from APT repository elasticsearch/kibana
    shell: |
      sudo apt-get install apt-transport-https
      echo "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main" | sudo tee /etc/apt/sources.list.d/elastic-8.x.list
      sudo apt-get update && sudo apt-get install elasticsearch -yy
      sudo apt-get update && sudo apt-get install kibana -yy

  - name: enable and start elasticsearch/kibana
    shell: |
      sudo systemctl enable elasticsearch kibana && sudo systemctl start elasticsearch kibana
      #sudo systemctl enable kibana && sudo systemctl start kibana

       
     
       

