---
- hosts: client_dev_pages
  become: true
  become_user: root
  tasks:

  - name: install filebeat
    shell: |
      curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.7.1-amd64.deb
      sudo dpkg -i filebeat-8.7.1-amd64.deb

       
     
       

