---
#changethis
- hosts: client_dev_pages
  become: true
  become_user: root

  vars:
  #changethis
    ipaddress: "192.168.1.91"
  tasks:

  - name: install filebeat
    shell: |
      curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.7.1-amd64.deb
      sudo dpkg -i filebeat-8.7.1-amd64.deb

  - name: Copy filebeat.yml
    copy:
      src: "filebeat.yml"
      dest: "/etc/filebeat/filebeat.yml"
      mode: 0600
      owner: root
      group: root

  - name: Change kibana ip address
    lineinfile:
     dest: /etc/filebeat/filebeat.yml
     regexp: '  host: "http://192.168.1.90:5601"'
     line: '  host: "http://{{ ipaddress }}:5601"'
     state: present

  - name: Change elasticsearch ip address
    lineinfile:
     dest: /etc/filebeat/filebeat.yml
     regexp: '  hosts: "http://192.168.1.90:9200"'
     line: '  hosts: ["http://{{ ipaddress }}:9200"]'
     state: present

  - name: restart filebeat
    shell: |
     systemctl restart filebeat



       
     
       

