---
#changethis
- hosts: client_dev_pages
  become: true
  become_user: root
  
  vars:
    #changethis
    module_name: "system"
    filename: "{{ module_name }}.yml"
  tasks:

  - name: enable module filebeat
    shell: |
     filebeat modules enable {{ module_name }}

  - name: Copy module configuration
    copy:
      src: "{{ filename }}"
      dest: "/etc/filebeat/modules.d/{{ filename }}"
      mode: 0644
      owner: root
      group: root

  - name: restart filebeat
    shell: |
     systemctl restart filebeat

